export const inventoryItems = [
  {
    name: "Pastillas de freno delanteras",
    brand: "Brembo",
    photos: [
      "https://picsum.photos/seed/brakes-front/80/80",
      "https://picsum.photos/seed/brakes-back/80/80",
      "https://picsum.photos/seed/brakes-box/80/80",
    ],
    entryDate: "2026-08-04",
    partNumber: "REP-001",
    models: "Corolla, Yaris",
    years: "2018-2024",
    currentStock: 14,
    minStock: 10,
    shelf: "Anaquel 12",
    warehouse: "Bodega 1",
    unitPrice: 45.5,
  },
  {
    name: "Filtro de aceite Toyota",
    brand: "Denso",
    photos: [
      "https://picsum.photos/seed/oilfilter-front/80/80",
      "https://picsum.photos/seed/oilfilter-label/80/80",
    ],
    entryDate: "2026-08-08",
    partNumber: "REP-002",
    models: "Hilux, RAV4",
    years: "2017-2023",
    currentStock: 2,
    minStock: 4,
    shelf: "Anaquel 4",
    warehouse: "Bodega 1",
    unitPrice: 8.75,
  },
  {
    name: "Bujía de encendido NGK",
    brand: "NGK",
    photos: [
      "https://picsum.photos/seed/sparkplug-front/80/80",
      "https://picsum.photos/seed/sparkplug-box/80/80",
    ],
    entryDate: "2026-08-11",
    partNumber: "REP-003",
    models: "Civic, Fit",
    years: "2016-2022",
    currentStock: 70,
    minStock: 50,
    shelf: "Anaquel 8",
    warehouse: "Bodega 2",
    unitPrice: 6.4,
  },
  {
    name: "Batería automotriz 12V 65Ah",
    brand: "LTH",
    photos: [
      "https://picsum.photos/seed/car-battery-front/80/80",
      "https://picsum.photos/seed/car-battery-label/80/80",
      "https://picsum.photos/seed/car-battery-side/80/80",
    ],
    entryDate: "2026-08-15",
    partNumber: "REP-004",
    models: "Mazda 3, CX-5",
    years: "2019-2024",
    currentStock: 8,
    minStock: 8,
    shelf: "Anaquel 2",
    warehouse: "Bodega 2",
    unitPrice: 112.3,
  },
];
